import { useState } from 'react';
import { supabase, isDemoMode, demoSession } from '../lib/supabase';
import { Button } from './ui/button';
import { Card } from './ui/card';
import { apiRequest } from '../lib/api';
import MarkdownView from './ui/MarkdownView';

const TOOLS = [
  { title: 'Export notes', desc: 'Save summary as Markdown', action: 'export', pro: false },
  { title: 'Explain selection', desc: 'Highlight text & explain with AI', action: 'selection', pro: false },
  { title: 'Translate', desc: 'Translate to 15+ languages', action: 'translate', pro: false },
  { title: 'Quiz generator', desc: 'Interactive 5 MCQs from content', action: 'quiz', pro: false },
  { title: 'Concept map', desc: 'Structured mind map of key ideas', action: 'mindmap', pro: false },
];

const LANGUAGES = ['Spanish', 'French', 'German', 'Italian', 'Portuguese', 'Chinese', 'Japanese', 'Korean', 'Hindi', 'Arabic', 'Russian', 'Turkish', 'Dutch', 'Swedish', 'Polish'];

export default function ToolsTab({ summaryData, pageContext, userPlan, rawContent, currentModel }) {
  const isPro = userPlan?.plan === 'pro';
  const [active, setActive] = useState(null);
  const [result, setResult] = useState(null);
  const [copied, setCopied] = useState(false);
  const [translating, setTranslating] = useState(false);
  const [selectedLang, setSelectedLang] = useState('');
  const [explaining, setExplaining] = useState(false);
  const [explanation, setExplanation] = useState('');

  async function getToken() {
    if (isDemoMode) return demoSession.access_token;
    const { data: { session } } = await supabase.auth.getSession();
    return session?.access_token;
  }

  async function handleTool(action) {
    if (!summaryData && action !== 'selection' && action !== 'export') {
      setResult({ type: 'empty' });
      return;
    }

    const token = await getToken();

    if (action === 'export') {
      const content = `# ${pageContext.title || 'Page Summary'}

**URL:** ${pageContext.url || 'N/A'}
**Generated by PagePal AI** (Model: ${currentModel})
**Reading Time:** ${summaryData?.readingTime || 'N/A'} | **Sentiment:** ${summaryData?.sentiment || 'N/A'}

## Summary
${summaryData?.summary || 'No summary available.'}

## Key Takeaways
${summaryData?.keyPoints?.map((p, i) => `${i + 1}. ${p}`).join('\n') || '- None'}

${summaryData?.timestamps?.length ? `## Chapters / Timestamps\n${summaryData.timestamps.map(t => `- **${t.time}**: ${t.label}`).join('\n')}\n` : ''}
---
*Exported on ${new Date().toLocaleDateString()}*
`;
      const blob = new Blob([content], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${(pageContext.title || 'pagepal_notes').slice(0, 40).replace(/[^a-zA-Z0-9]/g, '_')}.md`;
      a.click();
      URL.revokeObjectURL(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
      return;
    }

    if (action === 'selection') {
      setExplanation('');
      try {
        const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
        const results = await chrome.scripting.executeScript({
          target: { tabId: tab.id },
          func: () => window.getSelection()?.toString() || ''
        });
        const text = results[0]?.result?.trim();
        setResult({ type: 'selection', data: text || null });
      } catch {
        setResult({ type: 'selection', data: null });
      }
      return;
    }

    if (action === 'translate') {
      setResult({ type: 'translate-picker' });
      return;
    }

    if (action === 'quiz') {
      setActive('quiz');
      try {
        const effectiveContent = rawContent || summaryData?.summary || JSON.stringify(summaryData);
        const data = await apiRequest(
          '/api/quiz',
          {
            method: 'POST',
            body: JSON.stringify({
              content: effectiveContent,
              title: pageContext.title,
              model: currentModel,
            }),
          },
          token
        );
        setResult({ type: 'quiz', data: data.questions || [] });
      } catch (err) {
        if (err.upgrade) {
          setResult({ type: 'upgrade-required', action: 'quiz', message: err.data?.message });
        } else {
          setResult({ type: 'quiz', data: [] });
        }
      } finally {
        setActive(null);
      }
      return;
    }

    if (action === 'mindmap') {
      setActive('mindmap');
      try {
        const effectiveContent = summaryData ? `Summary: ${summaryData.summary}\n\nKey points:\n${summaryData.keyPoints?.join('\n')}` : rawContent;
        const promptText = `Generate a structured concept breakdown for: "${pageContext.title}".
Format the response with Markdown hierarchy:
# Central Theme: [Main Topic]
## 1. Core Pillar: [Name]
- Sub-concept / insight
- Supporting fact or mechanism
## 2. Core Pillar: [Name]
- Sub-concept / insight
- Supporting fact
## 3. Core Pillar: [Name]
- Sub-concept / insight
- Future implication or takeaway

Keep it crisp and structured.`;

        const data = await apiRequest(
          '/api/chat',
          {
            method: 'POST',
            body: JSON.stringify({
              messages: [{ role: 'user', content: promptText }],
              context: effectiveContent,
              pageType: pageContext.pageType,
              title: pageContext.title,
              model: currentModel,
            }),
          },
          token
        );
        setResult({ type: 'mindmap', data: data.reply });
      } catch (err) {
        setResult({ type: 'mindmap', data: 'Failed to generate concept map. ' + err.message });
      } finally {
        setActive(null);
      }
      return;
    }

    setResult({ type: 'coming-soon', action });
  }

  async function explainSelectionText(text) {
    if (!text || explaining) return;
    setExplaining(true);
    try {
      const token = await getToken();
      const data = await apiRequest(
        '/api/chat',
        {
          method: 'POST',
          body: JSON.stringify({
            messages: [{ role: 'user', content: `Please explain this highlighted passage clearly and concisely in plain English:\n\n"${text}"` }],
            context: rawContent || summaryData?.summary || '',
            pageType: 'selection',
            title: pageContext.title,
            model: currentModel,
          }),
        },
        token
      );
      setExplanation(data.reply);
    } catch (err) {
      setExplanation('Failed to explain text: ' + err.message);
    } finally {
      setExplaining(false);
    }
  }

  async function handleTranslate(lang) {
    setSelectedLang(lang);
    setTranslating(true);
    try {
      const token = await getToken();
      const textToTranslate = `Summary:\n${summaryData?.summary || ''}\n\nKey Takeaways:\n${summaryData?.keyPoints?.map((p, i) => `${i + 1}. ${p}`).join('\n') || ''}`;
      const data = await apiRequest(
        '/api/translate',
        {
          method: 'POST',
          body: JSON.stringify({
            text: textToTranslate,
            targetLanguage: lang,
            model: currentModel,
          }),
        },
        token
      );
      setResult({ type: 'translation', data: data.translation, lang });
    } catch (err) {
      if (err.upgrade) {
        setResult({ type: 'upgrade-required', action: 'translate', message: err.data?.message });
      } else {
        setResult({ type: 'translation', data: `Translation error: ${err.message}`, lang });
      }
    } finally {
      setTranslating(false);
    }
  }

  if (result?.type === 'quiz') return <QuizView questions={result.data} onBack={() => setResult(null)} />;
  
  if (result?.type === 'mindmap') {
    return (
      <div className="flex h-full flex-col gap-3 overflow-y-auto p-3 animate-fade-in">
        <Button variant="ghost" size="sm" onClick={() => setResult(null)} className="self-start rounded-full">← Back</Button>
        <span className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">Concept & Mind Map</span>
        <Card className="rounded-xl p-4 shadow-sm">
          <MarkdownView content={result.data} />
        </Card>
      </div>
    );
  }

  if (result?.type === 'empty') {
    return (
      <div className="flex h-full flex-col items-center justify-center gap-3 p-6 text-center">
        <p className="text-sm font-medium">No page summary yet</p>
        <p className="text-xs leading-5 text-muted-foreground">Summarize the page first on the Summary tab, then access AI tools.</p>
        <Button variant="outline" size="sm" onClick={() => setResult(null)} className="rounded-full">Back</Button>
      </div>
    );
  }

  if (result?.type === 'translate-picker') {
    return (
      <div className="flex h-full flex-col gap-3 overflow-y-auto p-3 animate-fade-in">
        <Button variant="ghost" size="sm" onClick={() => setResult(null)} className="self-start rounded-full">← Back</Button>
        <span className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">Select language</span>
        {translating && (
          <span className="flex items-center gap-2 text-xs text-muted-foreground">
            <span className="h-3 w-3 animate-spin rounded-full border-2 border-muted-foreground/30 border-t-foreground" />
            Translating with {currentModel.split('/')[1]?.split(':')[0] || 'AI'}…
          </span>
        )}
        <div className="grid grid-cols-2 gap-2">
          {LANGUAGES.map((lang) => (
            <button
              key={lang}
              onClick={() => handleTranslate(lang)}
              disabled={translating}
              className={`rounded-xl border p-3 text-left text-xs font-semibold transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring ${
                selectedLang === lang && translating
                  ? 'border-foreground bg-foreground text-background'
                  : 'border-border bg-card hover:bg-accent hover:text-foreground'
              }`}
            >
              {lang}
            </button>
          ))}
        </div>
      </div>
    );
  }

  if (result?.type === 'translation') {
    return (
      <div className="flex h-full flex-col gap-3 overflow-y-auto p-3 animate-fade-in">
        <Button variant="ghost" size="sm" onClick={() => setResult(null)} className="self-start rounded-full">← Back</Button>
        <span className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">Translated to {result.lang}</span>
        <Card className="rounded-xl p-4 shadow-sm">
          <MarkdownView content={result.data} />
        </Card>
      </div>
    );
  }

  if (result?.type === 'selection') {
    return (
      <div className="flex h-full flex-col gap-3 overflow-y-auto p-3 animate-fade-in">
        <Button variant="ghost" size="sm" onClick={() => setResult(null)} className="self-start rounded-full">← Back</Button>
        <span className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">Highlighted Text</span>
        <Card className="rounded-xl p-4">
          {result.data ? (
            <div className="flex flex-col gap-3">
              <p className="text-xs italic leading-5 text-muted-foreground border-l-2 border-primary pl-2.5">
                "{result.data}"
              </p>
              <Button
                size="sm"
                onClick={() => explainSelectionText(result.data)}
                disabled={explaining}
                className="w-full rounded-full font-bold shadow-hard-sm"
              >
                {explaining ? '✨ Explaining with AI…' : '✨ Explain Highlighted Text'}
              </Button>
            </div>
          ) : (
            <p className="text-xs text-muted-foreground">
              No text is currently selected. Highlight any text on the webpage and tap "Explain selection" again.
            </p>
          )}
        </Card>

        {explanation && (
          <Card className="rounded-xl p-4 shadow-sm animate-fade-in">
            <div className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1.5">AI Explanation</div>
            <MarkdownView content={explanation} />
          </Card>
        )}
      </div>
    );
  }

  if (result?.type === 'upgrade-required') {
    return (
      <div className="flex h-full flex-col items-center justify-center gap-4 p-6 text-center animate-fade-in">
        <span className="rounded-full border border-warning bg-warning/10 px-3 py-1 text-xs font-semibold text-warning">Pro required</span>
        <p className="max-w-[260px] text-sm font-medium leading-5">{result.message || 'Upgrade to Pro to use this feature.'}</p>
        <Button
          className="rounded-full shadow-hard-sm"
          onClick={async () => {
            const token = await getToken();
            const d = await apiRequest('/api/billing/create-checkout', { method: 'POST' }, token);
            if (d.url) window.open(d.url, '_blank');
          }}
        >
          Upgrade — $9/mo
        </Button>
        <Button variant="ghost" size="sm" onClick={() => setResult(null)} className="rounded-full">Back</Button>
      </div>
    );
  }

  return (
    <div className="flex h-full flex-col gap-3 overflow-y-auto p-3 animate-fade-in">
      <div className="flex flex-col gap-2">
        {TOOLS.map((t) => {
          const isDisabled = (!summaryData && t.action !== 'selection' && t.action !== 'export') || active === t.action;
          return (
            <div key={t.action} className="flex items-center gap-3 rounded-xl border border-border bg-card p-3 shadow-sm transition-colors hover:bg-accent/30">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <span className="text-xs font-bold">{t.title}</span>
                  {t.pro && <span className="rounded-full border border-border bg-muted px-2 py-0.5 text-[10px] font-bold text-muted-foreground">Pro</span>}
                </div>
                <p className="mt-0.5 text-xs leading-4 text-muted-foreground">{t.desc}</p>
                {isDisabled && !summaryData && t.action !== 'selection' && t.action !== 'export' && (
                  <p className="mt-1 text-[11px] font-semibold text-amber-500">Summarize page first</p>
                )}
              </div>
              <Button
                variant="secondary"
                size="sm"
                disabled={active === t.action}
                onClick={() => handleTool(t.action)}
                className="shrink-0 rounded-full font-bold px-3"
              >
                {active === t.action ? <span className="h-3 w-3 animate-spin rounded-full border-2 border-current border-t-transparent" aria-hidden /> : 'Open'}
              </Button>
            </div>
          );
        })}
      </div>
      {copied && (
        <div className="rounded-full border border-success bg-success/10 px-3 py-2 text-center text-xs font-semibold text-success animate-fade-in">
          Notes exported as Markdown ✓
        </div>
      )}
    </div>
  );
}

function QuizView({ questions, onBack }) {
  const [current, setCurrent] = useState(0);
  const [selected, setSelected] = useState(null);
  const [score, setScore] = useState(0);
  const [done, setDone] = useState(false);

  if (!questions?.length) {
    return (
      <div className="flex h-full flex-col items-center justify-center gap-4 p-6 text-center">
        <p className="text-sm font-bold">Quiz could not be generated</p>
        <p className="text-xs text-muted-foreground">Ensure the page has enough text content and try again.</p>
        <Button variant="outline" size="sm" onClick={onBack} className="rounded-full">Back</Button>
      </div>
    );
  }

  function choose(opt) {
    if (selected !== null) return;
    setSelected(opt);
    if (opt === questions[current].answer) setScore((s) => s + 1);
    setTimeout(() => {
      if (current + 1 < questions.length) { setCurrent((c) => c + 1); setSelected(null); }
      else setDone(true);
    }, 1400);
  }

  const q = questions[current];

  return (
    <div className="flex h-full flex-col gap-4 overflow-y-auto p-3 animate-fade-in">
      <Button variant="ghost" size="sm" onClick={onBack} className="self-start rounded-full">← Back</Button>
      {!done ? (
        <>
          <div className="flex items-center gap-3">
            <div className="h-2 flex-1 overflow-hidden rounded-full border border-border bg-muted">
              <div className="h-full bg-foreground transition-all duration-300" style={{ width: `${((current + 1) / questions.length) * 100}%` }} />
            </div>
            <span className="rounded-full bg-muted px-2 py-1 text-xs font-bold text-muted-foreground">{current + 1}/{questions.length}</span>
          </div>
          <p className="text-xs font-bold leading-5">{q.q}</p>
          <div className="flex flex-col gap-2">
            {q.options.map((opt, idx) => {
              let cls = 'border-border bg-card hover:bg-accent hover:text-foreground';
              if (selected !== null) {
                if (opt === q.answer) cls = 'border-success bg-success/10 text-success font-bold';
                else if (opt === selected) cls = 'border-destructive bg-destructive/10 text-destructive';
                else cls = 'border-border bg-card opacity-60';
              }
              return (
                <button
                  key={idx}
                  onClick={() => choose(opt)}
                  disabled={selected !== null}
                  className={`rounded-xl border p-3 text-left text-xs leading-5 transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring ${cls}`}
                >
                  <span className="mr-2 font-bold">{String.fromCharCode(65 + idx)}.</span>{opt}
                </button>
              );
            })}
          </div>
          {selected !== null && q.explanation && (
            <Card className="rounded-xl p-3 animate-fade-in">
              <div className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Explanation</div>
              <p className="mt-1 text-xs leading-5 text-muted-foreground">{q.explanation}</p>
              <Button
                variant="outline"
                size="sm"
                className="mt-3 w-full rounded-full font-bold"
                onClick={() => {
                  if (current + 1 < questions.length) { setCurrent((c) => c + 1); setSelected(null); }
                  else setDone(true);
                }}
              >
                {current + 1 < questions.length ? 'Next Question →' : 'See Results'}
              </Button>
            </Card>
          )}
          {selected === null && (
            <p className="text-center text-[10px] text-muted-foreground">Select an option to answer</p>
          )}
        </>
      ) : (
        <div className="flex flex-col items-center gap-4 py-8 text-center animate-fade-in">
          <span className={`rounded-full border px-4 py-1.5 text-sm font-black ${score >= 4 ? 'border-success bg-success/10 text-success' : score >= 2 ? 'border-warning bg-warning/10 text-warning' : 'border-destructive bg-destructive/10 text-destructive'}`}>
            {score} / {questions.length} Correct
          </span>
          <p className="text-xs font-medium text-muted-foreground">{score >= 4 ? 'Outstanding knowledge! 🎉' : score >= 2 ? 'Good grasp of the concepts!' : 'Review the summary and try again.'}</p>
          <div className="flex gap-2">
            <Button onClick={() => { setCurrent(0); setSelected(null); setScore(0); setDone(false); }} className="rounded-full font-bold">Try Again</Button>
            <Button variant="outline" onClick={onBack} className="rounded-full">Back to Tools</Button>
          </div>
        </div>
      )}
    </div>
  );
}
