import { useState } from 'react';
import { supabase } from '../lib/supabase';

const TOOLS = [
  { icon: '📄', title: 'Export Notes', desc: 'Save as Markdown or copy to clipboard', action: 'export', pro: false },
  { icon: '🌐', title: 'Translate', desc: 'Translate summary to 50+ languages', action: 'translate', pro: true },
  { icon: '🎯', title: 'Quiz Me', desc: 'Auto-generate 5 MCQs from this content', action: 'quiz', pro: true },
  { icon: '📊', title: 'Mind Map', desc: 'Visualize key concepts as a mind map', action: 'mindmap', pro: true },
  { icon: '✂️', title: 'Explain Selection', desc: 'Highlight any text on page, then click here', action: 'selection', pro: false },
  { icon: '🔗', title: 'Share Summary', desc: 'Generate a shareable link with AI summary', action: 'share', pro: true },
];

const LANGUAGES = [
  'Spanish', 'French', 'German', 'Italian', 'Portuguese', 'Chinese', 'Japanese',
  'Korean', 'Hindi', 'Arabic', 'Russian', 'Turkish', 'Dutch', 'Swedish', 'Polish'
];

export default function ToolsTab({ summaryData, pageContext, user }) {
  const [activeAction, setActiveAction] = useState(null);
  const [result, setResult] = useState(null);
  const [copied, setCopied] = useState(false);
  const [translating, setTranslating] = useState(false);
  const [selectedLang, setSelectedLang] = useState('');

  async function handleTool(action) {
    if (!summaryData && action !== 'selection') {
      return;
    }

    const { data: { session } } = await supabase.auth.getSession();
    const token = session?.access_token;

    if (action === 'export') {
      const content = `# ${pageContext.title}\n\n## Summary\n${summaryData?.summary || 'No summary available'}\n\n## Key Points\n${summaryData?.keyPoints?.map(p => `- ${p}`).join('\n') || 'No key points'}\n\n---\n*Generated by PagePal AI*`;
      const blob = new Blob([content], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${(pageContext.title || 'pagepal-notes').slice(0, 40).replace(/[^a-zA-Z0-9]/g, '_')}.md`;
      a.click();
      URL.revokeObjectURL(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      return;
    }

    if (action === 'selection') {
      try {
        const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
        const results = await chrome.scripting.executeScript({
          target: { tabId: tab.id },
          func: () => window.getSelection()?.toString() || ''
        });
        const selectedText = results[0]?.result;
        if (selectedText) {
          chrome.storage.session.set({ selectedText });
          setResult({ type: 'selection', data: selectedText });
        } else {
          setResult({ type: 'selection', data: null });
        }
      } catch (err) {
        console.error('Selection extraction failed:', err);
      }
      return;
    }

    if (action === 'translate') {
      setResult({ type: 'translate-picker' });
      return;
    }

    if (action === 'quiz') {
      setActiveAction('quiz');
      try {
        const res = await fetch(`${import.meta.env.VITE_PROXY_URL}/api/quiz`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
          body: JSON.stringify({
            content: JSON.stringify(summaryData),
            title: pageContext.title
          })
        });
        const data = await res.json();
        setResult({ type: 'quiz', data: data.questions });
      } catch (err) {
        console.error('Quiz generation failed:', err);
      } finally {
        setActiveAction(null);
      }
      return;
    }

    // Generic unimplemented tool
    setResult({ type: 'coming-soon', action });
  }

  async function handleTranslate(lang) {
    setSelectedLang(lang);
    setTranslating(true);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      const res = await fetch(`${import.meta.env.VITE_PROXY_URL}/api/translate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session?.access_token}`
        },
        body: JSON.stringify({
          text: `Summary: ${summaryData?.summary}\n\nKey Points:\n${summaryData?.keyPoints?.join('\n')}`,
          targetLanguage: lang
        })
      });
      const data = await res.json();
      setResult({ type: 'translation', data: data.translation, lang });
    } catch (err) {
      console.error('Translation failed:', err);
    } finally {
      setTranslating(false);
    }
  }

  // Render results
  if (result?.type === 'quiz') {
    return <QuizView questions={result.data} onBack={() => setResult(null)} />;
  }

  if (result?.type === 'translate-picker') {
    return (
      <div className="overflow-y-auto h-full p-3 animate-fade-in">
        <button onClick={() => setResult(null)} className="text-purple-400 text-xs mb-3 hover:underline flex items-center gap-1">
          ← Back to tools
        </button>
        <h3 className="text-xs font-bold uppercase tracking-wider text-gray-400 mb-3">Select Language</h3>
        <div className="grid grid-cols-2 gap-2">
          {LANGUAGES.map(lang => (
            <button
              key={lang}
              onClick={() => handleTranslate(lang)}
              disabled={translating}
              className={`px-3 py-2.5 rounded-xl text-xs font-medium text-left transition-all btn-hover-lift ${
                selectedLang === lang && translating
                  ? 'bg-purple-600/20 border border-purple-500/50 text-purple-300'
                  : 'bg-dark-700 border border-dark-500/30 text-gray-300 hover:border-purple-600/50 hover:bg-dark-600'
              } disabled:opacity-50`}
            >
              {lang}
              {selectedLang === lang && translating && (
                <span className="ml-1 animate-spin inline-block">⚙️</span>
              )}
            </button>
          ))}
        </div>
      </div>
    );
  }

  if (result?.type === 'translation') {
    return (
      <div className="overflow-y-auto h-full p-3 animate-fade-in">
        <button onClick={() => setResult(null)} className="text-purple-400 text-xs mb-3 hover:underline flex items-center gap-1">
          ← Back to tools
        </button>
        <div className="flex items-center gap-2 mb-3">
          <span className="text-sm">🌐</span>
          <h3 className="text-xs font-bold uppercase tracking-wider text-gray-400">
            Translated to {result.lang}
          </h3>
        </div>
        <div className="glass rounded-xl p-4">
          <p className="text-sm text-gray-200 leading-relaxed whitespace-pre-wrap">{result.data}</p>
        </div>
      </div>
    );
  }

  if (result?.type === 'selection') {
    return (
      <div className="overflow-y-auto h-full p-3 animate-fade-in">
        <button onClick={() => setResult(null)} className="text-purple-400 text-xs mb-3 hover:underline flex items-center gap-1">
          ← Back to tools
        </button>
        <div className="glass rounded-xl p-4">
          {result.data ? (
            <>
              <h3 className="text-xs font-bold text-purple-400 mb-2">Selected Text</h3>
              <p className="text-sm text-gray-200 leading-relaxed">{result.data}</p>
            </>
          ) : (
            <p className="text-sm text-gray-400">No text selected. Highlight text on the page first, then try again.</p>
          )}
        </div>
      </div>
    );
  }

  if (result?.type === 'coming-soon') {
    return (
      <div className="flex flex-col items-center justify-center h-full p-8 gap-4 animate-fade-in">
        <div className="text-5xl">🚧</div>
        <p className="text-white font-bold">Coming Soon</p>
        <p className="text-gray-500 text-xs text-center">This feature is under development and will be available in the next update.</p>
        <button onClick={() => setResult(null)} className="px-4 py-2 rounded-xl bg-purple-600 text-white text-xs font-semibold hover:bg-purple-500 transition">
          Go Back
        </button>
      </div>
    );
  }

  // Default: Tool list
  return (
    <div className="overflow-y-auto h-full p-3">
      <div className="flex flex-col gap-2.5">
        {TOOLS.map((tool, i) => (
          <button
            key={tool.action}
            onClick={() => handleTool(tool.action)}
            disabled={activeAction === tool.action}
            className="flex items-start gap-3 p-3 rounded-xl bg-dark-700/50 border border-dark-500/30 hover:border-purple-700/50 hover:bg-dark-600/50 transition-all text-left disabled:opacity-50 group btn-hover-lift animate-slide-up"
            style={{ animationDelay: `${i * 40}ms` }}
          >
            <span className="text-2xl group-hover:scale-110 transition-transform">{tool.icon}</span>
            <div className="flex-1">
              <div className="flex items-center gap-2">
                <p className="text-purple-300 font-bold text-sm">{tool.title}</p>
                {tool.pro && (
                  <span className="px-1.5 py-0.5 rounded-md text-[8px] font-bold uppercase bg-gradient-to-r from-amber-500/20 to-orange-500/20 border border-amber-500/30 text-amber-400">
                    Pro
                  </span>
                )}
              </div>
              <p className="text-gray-500 text-xs mt-0.5">{tool.desc}</p>
            </div>
            {activeAction === tool.action ? (
              <span className="text-purple-400 animate-spin text-lg">⚙️</span>
            ) : (
              <span className="text-gray-600 text-xs group-hover:text-purple-400 transition-all">→</span>
            )}
          </button>
        ))}
      </div>

      {/* Copied toast */}
      {copied && (
        <div className="fixed bottom-20 left-1/2 -translate-x-1/2 px-4 py-2 rounded-xl bg-green-600 text-white text-xs font-semibold animate-fade-in z-50">
          ✓ Notes exported!
        </div>
      )}
    </div>
  );
}

function QuizView({ questions, onBack }) {
  const [current, setCurrent] = useState(0);
  const [selected, setSelected] = useState(null);
  const [score, setScore] = useState(0);
  const [done, setDone] = useState(false);

  if (!questions?.length) {
    return (
      <div className="flex flex-col items-center justify-center h-full p-8 gap-4 animate-fade-in">
        <div className="text-5xl">❌</div>
        <p className="text-white font-bold">Quiz Generation Failed</p>
        <p className="text-gray-500 text-xs text-center">Couldn't generate questions. Try again with different content.</p>
        <button onClick={onBack} className="px-4 py-2 rounded-xl bg-purple-600 text-white text-xs font-semibold hover:bg-purple-500 transition">
          Go Back
        </button>
      </div>
    );
  }

  function choose(opt) {
    if (selected !== null) return;
    setSelected(opt);
    if (opt === questions[current].answer) setScore(s => s + 1);
    setTimeout(() => {
      if (current + 1 < questions.length) {
        setCurrent(c => c + 1);
        setSelected(null);
      } else {
        setDone(true);
      }
    }, 1200);
  }

  const q = questions[current];

  return (
    <div className="overflow-y-auto h-full p-3 animate-fade-in">
      <button onClick={onBack} className="text-purple-400 text-xs mb-4 hover:underline flex items-center gap-1">
        ← Back to tools
      </button>

      {!done ? (
        <div>
          {/* Progress Bar */}
          <div className="flex items-center gap-3 mb-4">
            <div className="flex-1 h-1.5 bg-dark-700 rounded-full overflow-hidden">
              <div
                className="h-full bg-gradient-to-r from-purple-600 to-indigo-600 rounded-full transition-all duration-500"
                style={{ width: `${((current + 1) / questions.length) * 100}%` }}
              />
            </div>
            <span className="text-xs text-gray-500 font-mono">{current + 1}/{questions.length}</span>
          </div>

          {/* Question */}
          <p className="text-white font-semibold mb-4 text-sm leading-relaxed">{q.q}</p>

          {/* Options */}
          <div className="space-y-2">
            {q.options.map((opt, idx) => {
              let style = 'bg-dark-700 border-dark-500/30 text-gray-300 hover:border-purple-600/50';
              if (selected !== null) {
                if (opt === q.answer) style = 'bg-green-900/30 border-green-500/50 text-green-300';
                else if (opt === selected) style = 'bg-red-900/30 border-red-500/50 text-red-300';
                else style = 'bg-dark-700 border-dark-500/30 text-gray-500 opacity-60';
              }

              return (
                <button
                  key={idx}
                  onClick={() => choose(opt)}
                  disabled={selected !== null}
                  className={`w-full text-left px-3.5 py-2.5 rounded-xl text-sm border transition-all ${style} disabled:cursor-default`}
                >
                  <span className="text-xs font-bold text-gray-500 mr-2">
                    {String.fromCharCode(65 + idx)}.
                  </span>
                  {opt}
                </button>
              );
            })}
          </div>

          {/* Explanation */}
          {selected !== null && q.explanation && (
            <div className="mt-3 p-3 rounded-xl bg-dark-700/50 border border-dark-500/30 animate-slide-up">
              <p className="text-[10px] font-bold uppercase tracking-wider text-purple-400 mb-1">Explanation</p>
              <p className="text-xs text-gray-400 leading-relaxed">{q.explanation}</p>
            </div>
          )}
        </div>
      ) : (
        <div className="text-center py-8 animate-fade-in">
          <div className="text-6xl mb-4">{score >= 4 ? '🏆' : score >= 2 ? '👍' : '📚'}</div>
          <p className="text-white font-bold text-2xl mb-1">{score} / {questions.length}</p>
          <p className="text-gray-500 text-sm">
            {score >= 4 ? 'Excellent work! You really know this material.' : score >= 2 ? 'Good effort! Room for improvement.' : 'Keep studying! Try reading the content again.'}
          </p>

          {/* Score Bar */}
          <div className="w-48 mx-auto mt-4 h-2 bg-dark-700 rounded-full overflow-hidden">
            <div
              className={`h-full rounded-full transition-all duration-1000 ${
                score >= 4 ? 'bg-gradient-to-r from-green-500 to-emerald-500' :
                score >= 2 ? 'bg-gradient-to-r from-yellow-500 to-orange-500' :
                'bg-gradient-to-r from-red-500 to-pink-500'
              }`}
              style={{ width: `${(score / questions.length) * 100}%` }}
            />
          </div>

          <button
            onClick={() => { setCurrent(0); setSelected(null); setScore(0); setDone(false); }}
            className="mt-6 px-6 py-2.5 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 text-white text-sm font-semibold hover:opacity-90 transition btn-hover-lift glow-purple"
          >
            Try Again
          </button>
        </div>
      )}
    </div>
  );
}
