import { useState, useEffect } from 'react';
import { supabase, isDemoMode, demoSession } from '../lib/supabase';
import { Button } from './ui/button';
import { Card } from './ui/card';
import { apiRequest } from '../lib/api';
import MarkdownView from './ui/MarkdownView';

const TOOLS = [
  { id: 'export', title: 'Export notes', desc: 'Save & copy summary as Markdown', icon: '📝' },
  { id: 'selection', title: 'Explain selection', desc: 'Highlight text or paste to explain', icon: '🔍' },
  { id: 'translate', title: 'Translate', desc: 'Translate to 15+ languages with audio', icon: '🌐' },
  { id: 'quiz', title: 'Quiz generator', desc: 'Interactive 5 MCQs from content', icon: '🧠' },
  { id: 'mindmap', title: 'Concept map', desc: 'Structured mind map of key ideas', icon: '🗺️' },
];

const LANGUAGES = [
  { name: 'Spanish', code: 'es' },
  { name: 'French', code: 'fr' },
  { name: 'German', code: 'de' },
  { name: 'Japanese', code: 'ja' },
  { name: 'Chinese (Simplified)', code: 'zh' },
  { name: 'Hindi', code: 'hi' },
  { name: 'Arabic', code: 'ar' },
  { name: 'Italian', code: 'it' },
  { name: 'Portuguese', code: 'pt' },
  { name: 'Korean', code: 'ko' },
  { name: 'Russian', code: 'ru' },
  { name: 'Turkish', code: 'tr' },
  { name: 'Dutch', code: 'nl' },
  { name: 'Swedish', code: 'sv' },
  { name: 'Polish', code: 'pl' },
];

export default function ToolsTab({ summaryData, pageContext, userPlan, rawContent, currentModel }) {
  const [activeTool, setActiveTool] = useState(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [copied, setCopied] = useState(false);

  // Selection state
  const [selectedText, setSelectedText] = useState('');
  const [customText, setCustomText] = useState('');
  const [explainStyle, setExplainStyle] = useState('simple');
  const [explanation, setExplanation] = useState('');

  // Translate state
  const [translateSource, setTranslateSource] = useState('summary');
  const [selectedLang, setSelectedLang] = useState('Spanish');
  const [translatedText, setTranslatedText] = useState('');
  const [isSpeaking, setIsSpeaking] = useState(false);

  // Concept map state
  const [conceptMapData, setConceptMapData] = useState('');

  async function getToken() {
    if (isDemoMode) return demoSession.access_token;
    const { data: { session } } = await supabase.auth.getSession();
    return session?.access_token;
  }

  // Auto-detect highlighted text when selection tool opens
  useEffect(() => {
    if (activeTool === 'selection') {
      grabActiveSelection();
    }
  }, [activeTool]);

  async function grabActiveSelection() {
    try {
      if (typeof chrome !== 'undefined' && chrome.tabs?.query) {
        const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
        if (tab?.id) {
          const results = await chrome.scripting.executeScript({
            target: { tabId: tab.id },
            func: () => window.getSelection()?.toString() || '',
          });
          const text = results[0]?.result?.trim();
          if (text) {
            setSelectedText(text);
            setCustomText(text);
          }
        }
      }
    } catch {}
  }

  // 1. Export Notes Handler
  function generateMarkdownNotes() {
    const title = pageContext?.title || 'Webpage Analysis';
    const url = pageContext?.url || 'N/A';
    const model = currentModel || 'OpenRouter';
    const date = new Date().toLocaleDateString();

    if (summaryData) {
      return `# ${title}

**Source URL:** ${url}
**Generated by:** PagePal AI (${model})
**Reading Time:** ${summaryData.readingTime || 'N/A'} | **Sentiment:** ${summaryData.sentiment || 'Neutral'}

## 📌 Executive Summary
${summaryData.summary || 'N/A'}

## 🎯 Key Takeaways
${summaryData.keyPoints?.map((p, i) => `${i + 1}. ${p}`).join('\n') || '- None recorded.'}

${summaryData.timestamps?.length ? `## ⏱️ Chapters & Timestamps\n${summaryData.timestamps.map((t) => `- **${t.time}**: ${t.label}`).join('\n')}\n` : ''}
---
*Exported via PagePal AI on ${date}*
`;
    }

    // Fallback if not summarized yet
    return `# ${title}

**Source URL:** ${url}
**Extracted by:** PagePal AI (${model})
**Export Date:** ${date}

## 📄 Page Content Excerpt
${rawContent?.slice(0, 5000) || 'No content extracted.'}

---
*Exported via PagePal AI*
`;
  }

  function handleDownloadMarkdown() {
    const content = generateMarkdownNotes();
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(pageContext?.title || 'pagepal_notes').slice(0, 35).replace(/[^a-zA-Z0-9]/g, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
    triggerCopiedNotice();
  }

  function handleCopyMarkdown(text = null) {
    const toCopy = text || generateMarkdownNotes();
    navigator.clipboard.writeText(toCopy);
    triggerCopiedNotice();
  }

  function triggerCopiedNotice() {
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  // 2. Explain Selection / Custom Text Handler
  async function handleExplainText(style = explainStyle) {
    const textToExplain = customText.trim() || selectedText.trim();
    if (!textToExplain) return;

    setLoading(true);
    setExplanation('');
    try {
      const token = await getToken();
      let styleInstruction = '';
      if (style === 'simple') styleInstruction = 'Explain this in ultra-simple, plain English as if explaining to a beginner (ELI5 style).';
      else if (style === 'detailed') styleInstruction = 'Provide a rigorous, in-depth breakdown covering mechanics, implications, and nuance.';
      else if (style === 'bullets') styleInstruction = 'Break down this concept into 3-5 crisp, punchy bullet points.';
      else if (style === 'analogy') styleInstruction = 'Explain this using a vivid, memorable real-world analogy.';

      const prompt = `Passage to explain:
"""
${textToExplain}
"""

Instruction: ${styleInstruction}
Provide a clear, structured response with markdown formatting.`;

      const data = await apiRequest(
        '/api/chat',
        {
          method: 'POST',
          body: JSON.stringify({
            messages: [{ role: 'user', content: prompt }],
            context: rawContent || summaryData?.summary || '',
            pageType: 'selection',
            title: pageContext?.title,
            model: currentModel,
          }),
        },
        token
      );
      setExplanation(data.reply);
    } catch (err) {
      setExplanation(`⚠️ Failed to explain: ${err.message}`);
    } finally {
      setLoading(false);
    }
  }

  // 3. Translation Handler
  async function handleTranslate(targetLang = selectedLang) {
    setSelectedLang(targetLang);
    setLoading(true);
    setTranslatedText('');
    try {
      const token = await getToken();
      let textToTranslate = '';

      if (translateSource === 'summary' && summaryData) {
        textToTranslate = `Summary:\n${summaryData.summary}\n\nKey Takeaways:\n${summaryData.keyPoints?.map((p, i) => `${i + 1}. ${p}`).join('\n') || ''}`;
      } else if (translateSource === 'custom' && customText.trim()) {
        textToTranslate = customText.trim();
      } else {
        textToTranslate = (summaryData?.summary || rawContent || pageContext?.title || '').slice(0, 4000);
      }

      const data = await apiRequest(
        '/api/translate',
        {
          method: 'POST',
          body: JSON.stringify({
            text: textToTranslate,
            targetLanguage: targetLang,
            model: currentModel,
          }),
        },
        token
      );
      setTranslatedText(data.translation);
    } catch (err) {
      setTranslatedText(`⚠️ Translation error: ${err.message}`);
    } finally {
      setLoading(false);
    }
  }

  function handleSpeakTranslation() {
    if (typeof window === 'undefined' || !window.speechSynthesis || !translatedText) return;
    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
      return;
    }

    const utterance = new SpeechSynthesisUtterance(translatedText.replace(/[#*`_]/g, ''));
    const langObj = LANGUAGES.find((l) => l.name === selectedLang);
    if (langObj) utterance.lang = langObj.code;

    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = () => setIsSpeaking(false);

    setIsSpeaking(true);
    window.speechSynthesis.speak(utterance);
  }

  // 4. Quiz Generator Handler
  async function handleGenerateQuiz() {
    setActiveTool('quiz');
    setLoading(true);
    setResult(null);
    try {
      const token = await getToken();
      const effectiveContent = rawContent || summaryData?.summary || pageContext?.title || 'General webpage text';
      const data = await apiRequest(
        '/api/quiz',
        {
          method: 'POST',
          body: JSON.stringify({
            content: effectiveContent.slice(0, 12000),
            title: pageContext?.title || 'Webpage Quiz',
            model: currentModel,
          }),
        },
        token
      );
      setResult({ type: 'quiz', data: data.questions || [] });
    } catch (err) {
      setResult({ type: 'quiz', data: [], error: err.message });
    } finally {
      setLoading(false);
    }
  }

  // 5. Concept Map Handler
  async function handleGenerateConceptMap() {
    setActiveTool('mindmap');
    setLoading(true);
    setConceptMapData('');
    try {
      const token = await getToken();
      const effectiveContent = summaryData
        ? `Summary: ${summaryData.summary}\n\nKey points:\n${summaryData.keyPoints?.join('\n')}`
        : rawContent?.slice(0, 8000) || pageContext?.title;

      const promptText = `Generate a structured hierarchical concept breakdown for "${pageContext?.title || 'Active Topic'}".
Structure it cleanly:
# 🌐 Central Theme: [Core Topic Title]
## 1. 🏛️ Core Pillar: [Pillar Name]
- **Key Mechanism:** [How it works]
- **Significance:** [Why it matters]
## 2. 🏛️ Core Pillar: [Pillar Name]
- **Key Mechanism:** [How it works]
- **Significance:** [Why it matters]
## 3. 🏛️ Core Pillar: [Pillar Name]
- **Key Mechanism:** [How it works]
- **Significance:** [Why it matters]
## 🚀 Future Takeaway & Practical Application
- [Key conclusion]`;

      const data = await apiRequest(
        '/api/chat',
        {
          method: 'POST',
          body: JSON.stringify({
            messages: [{ role: 'user', content: promptText }],
            context: effectiveContent,
            pageType: pageContext?.pageType || 'general',
            title: pageContext?.title,
            model: currentModel,
          }),
        },
        token
      );
      setConceptMapData(data.reply);
    } catch (err) {
      setConceptMapData(`⚠️ Failed to generate concept map: ${err.message}`);
    } finally {
      setLoading(false);
    }
  }

  // RENDER SPECIFIC SUB-VIEWS

  // --- Quiz View ---
  if (activeTool === 'quiz') {
    return (
      <div className="flex h-full flex-col gap-3 overflow-y-auto p-3 animate-fade-in">
        <Button variant="ghost" size="sm" onClick={() => setActiveTool(null)} className="self-start rounded-full">
          ← Back to Tools
        </Button>
        {loading ? (
          <div className="flex flex-1 flex-col items-center justify-center gap-3 py-12 text-center">
            <span className="h-6 w-6 animate-spin rounded-full border-2 border-primary border-t-transparent" />
            <span className="text-xs font-bold text-foreground">Generating 5 MCQs with AI…</span>
            <span className="text-[10px] text-muted-foreground">Extracting core concepts from the page</span>
          </div>
        ) : (
          <QuizView questions={result?.data} error={result?.error} onBack={() => setActiveTool(null)} onRetry={handleGenerateQuiz} />
        )}
      </div>
    );
  }

  // --- Concept Map View ---
  if (activeTool === 'mindmap') {
    return (
      <div className="flex h-full flex-col gap-3 overflow-y-auto p-3 animate-fade-in">
        <div className="flex items-center justify-between">
          <Button variant="ghost" size="sm" onClick={() => setActiveTool(null)} className="rounded-full">
            ← Back
          </Button>
          {conceptMapData && (
            <Button variant="outline" size="sm" onClick={() => handleCopyMarkdown(conceptMapData)} className="rounded-full text-xs font-bold">
              {copied ? '✓ Copied' : '📋 Copy Map'}
            </Button>
          )}
        </div>

        <div className="flex items-center justify-between">
          <span className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Concept & Mind Map</span>
          <span className="text-[10px] font-semibold text-emerald-600 dark:text-emerald-400">⚡ AI Generated</span>
        </div>

        {loading ? (
          <div className="flex flex-1 flex-col items-center justify-center gap-3 py-12 text-center">
            <span className="h-6 w-6 animate-spin rounded-full border-2 border-primary border-t-transparent" />
            <span className="text-xs font-bold text-foreground">Mapping core ideas & pillars…</span>
          </div>
        ) : (
          <Card className="rounded-2xl p-4 shadow-sm">
            <MarkdownView content={conceptMapData} />
          </Card>
        )}
      </div>
    );
  }

  // --- Export Notes View ---
  if (activeTool === 'export') {
    const notesContent = generateMarkdownNotes();
    return (
      <div className="flex h-full flex-col gap-3 overflow-y-auto p-3 animate-fade-in">
        <div className="flex items-center justify-between">
          <Button variant="ghost" size="sm" onClick={() => setActiveTool(null)} className="rounded-full">
            ← Back
          </Button>
          <div className="flex items-center gap-1.5">
            <Button variant="outline" size="sm" onClick={() => handleCopyMarkdown(notesContent)} className="rounded-full text-xs font-bold">
              {copied ? '✓ Copied' : '📋 Copy'}
            </Button>
            <Button size="sm" onClick={handleDownloadMarkdown} className="rounded-full text-xs font-bold shadow-hard-sm">
              ⬇ Download .md
            </Button>
          </div>
        </div>

        <div className="flex items-center justify-between">
          <span className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Markdown Notes Preview</span>
          {copied && <span className="text-[10px] font-bold text-emerald-600 animate-fade-in">✓ Copied to clipboard</span>}
        </div>

        <Card className="rounded-2xl p-4 shadow-sm font-mono text-xs">
          <MarkdownView content={notesContent} />
        </Card>
      </div>
    );
  }

  // --- Explain Selection View ---
  if (activeTool === 'selection') {
    return (
      <div className="flex h-full flex-col gap-3 overflow-y-auto p-3 animate-fade-in">
        <div className="flex items-center justify-between">
          <Button variant="ghost" size="sm" onClick={() => setActiveTool(null)} className="rounded-full">
            ← Back
          </Button>
          <Button variant="ghost" size="sm" onClick={grabActiveSelection} className="text-xs text-muted-foreground hover:text-foreground">
            🔄 Refresh Highlight
          </Button>
        </div>

        <div className="flex flex-col gap-2">
          <span className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
            {selectedText ? 'Selected / Custom Passage' : 'Enter Text to Explain'}
          </span>
          <textarea
            value={customText}
            onChange={(e) => setCustomText(e.target.value)}
            placeholder="Highlight any text on the webpage, or paste any paragraph, code, or sentence here to explain..."
            rows={4}
            className="w-full rounded-xl border border-border bg-card p-2.5 text-xs placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
          />

          {/* Explanation Style Pills */}
          <div className="flex flex-wrap gap-1.5 pt-1">
            {[
              { id: 'simple', label: '💡 Simple (ELI5)' },
              { id: 'detailed', label: '🔬 In-Depth' },
              { id: 'bullets', label: '📌 Key Bullets' },
              { id: 'analogy', label: '🎭 Analogy' },
            ].map((s) => (
              <button
                key={s.id}
                onClick={() => setExplainStyle(s.id)}
                className={`rounded-full px-2.5 py-1 text-[10px] font-bold transition-colors ${
                  explainStyle === s.id
                    ? 'bg-primary text-black border border-black shadow-xs'
                    : 'bg-muted/60 text-muted-foreground hover:bg-muted'
                }`}
              >
                {s.label}
              </button>
            ))}
          </div>

          <Button
            size="sm"
            onClick={() => handleExplainText(explainStyle)}
            disabled={loading || (!customText.trim() && !selectedText.trim())}
            className="w-full rounded-full font-bold shadow-hard-sm mt-1"
          >
            {loading ? '✨ Explaining with AI…' : '✨ Explain with AI'}
          </Button>
        </div>

        {explanation && (
          <Card className="rounded-2xl p-4 shadow-sm animate-fade-in mt-1">
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs font-bold uppercase tracking-wider text-muted-foreground">AI Explanation</span>
              <Button variant="ghost" size="sm" onClick={() => handleCopyMarkdown(explanation)} className="h-6 text-[10px] font-bold">
                {copied ? '✓ Copied' : '📋 Copy'}
              </Button>
            </div>
            <MarkdownView content={explanation} />
          </Card>
        )}
      </div>
    );
  }

  // --- Translate View ---
  if (activeTool === 'translate') {
    return (
      <div className="flex h-full flex-col gap-3 overflow-y-auto p-3 animate-fade-in">
        <Button variant="ghost" size="sm" onClick={() => setActiveTool(null)} className="self-start rounded-full">
          ← Back
        </Button>

        {/* Source selector */}
        <div className="flex items-center justify-between gap-1 rounded-xl bg-muted/40 p-1 border border-border/40">
          <button
            onClick={() => setTranslateSource('summary')}
            className={`flex-1 rounded-lg py-1 text-center text-xs font-bold transition-all ${
              translateSource === 'summary' ? 'bg-card text-foreground shadow-xs border border-border/50' : 'text-muted-foreground'
            }`}
          >
            Summary Takeaways
          </button>
          <button
            onClick={() => setTranslateSource('page')}
            className={`flex-1 rounded-lg py-1 text-center text-xs font-bold transition-all ${
              translateSource === 'page' ? 'bg-card text-foreground shadow-xs border border-border/50' : 'text-muted-foreground'
            }`}
          >
            Page Excerpt
          </button>
        </div>

        <div className="flex items-center justify-between">
          <span className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Select Target Language</span>
          {loading && (
            <span className="flex items-center gap-1.5 text-[10px] text-muted-foreground">
              <span className="h-3 w-3 animate-spin rounded-full border-2 border-muted-foreground/30 border-t-foreground" />
              Translating…
            </span>
          )}
        </div>

        {/* Language Grid */}
        <div className="grid grid-cols-3 gap-1.5">
          {LANGUAGES.map((lang) => (
            <button
              key={lang.name}
              onClick={() => handleTranslate(lang.name)}
              disabled={loading}
              className={`rounded-xl border p-2 text-center text-[11px] font-semibold transition-colors focus-visible:outline-none ${
                selectedLang === lang.name && translatedText
                  ? 'border-primary bg-primary/20 font-bold text-foreground'
                  : 'border-border/60 bg-card hover:bg-accent'
              }`}
            >
              {lang.name}
            </button>
          ))}
        </div>

        {translatedText && (
          <Card className="rounded-2xl p-4 shadow-sm animate-fade-in mt-1">
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
                Translated to {selectedLang}
              </span>
              <div className="flex items-center gap-1">
                <Button variant="ghost" size="sm" onClick={handleSpeakTranslation} className="h-6 text-[10px] font-bold">
                  {isSpeaking ? '⏹ Stop' : '🔊 Listen'}
                </Button>
                <Button variant="ghost" size="sm" onClick={() => handleCopyMarkdown(translatedText)} className="h-6 text-[10px] font-bold">
                  {copied ? '✓ Copied' : '📋 Copy'}
                </Button>
              </div>
            </div>
            <MarkdownView content={translatedText} />
          </Card>
        )}
      </div>
    );
  }

  // --- Default Tools Grid View ---
  return (
    <div className="flex h-full flex-col gap-3 overflow-y-auto p-3 animate-fade-in">
      <div className="flex flex-col gap-2">
        {TOOLS.map((t) => (
          <div
            key={t.id}
            className="flex items-center gap-3 rounded-2xl border border-border/80 bg-card p-3 shadow-sm transition-all hover:bg-accent/40"
          >
            <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-muted/60 text-sm" aria-hidden>
              {t.icon}
            </span>
            <div className="flex-1 min-w-0">
              <div className="text-xs font-bold text-foreground leading-tight">{t.title}</div>
              <p className="mt-0.5 text-[11px] leading-4 text-muted-foreground">{t.desc}</p>
            </div>
            <Button
              variant="secondary"
              size="sm"
              onClick={() => {
                if (t.id === 'quiz') handleGenerateQuiz();
                else if (t.id === 'mindmap') handleGenerateConceptMap();
                else setActiveTool(t.id);
              }}
              className="shrink-0 rounded-full font-bold px-3.5 h-7 text-xs shadow-xs"
            >
              Open
            </Button>
          </div>
        ))}
      </div>

      {copied && (
        <div className="rounded-full border border-success bg-success/10 px-3 py-1.5 text-center text-xs font-semibold text-success animate-fade-in">
          Copied to clipboard ✓
        </div>
      )}
    </div>
  );
}

function QuizView({ questions, error, onBack, onRetry }) {
  const [current, setCurrent] = useState(0);
  const [selected, setSelected] = useState(null);
  const [score, setScore] = useState(0);
  const [done, setDone] = useState(false);

  if (error || !questions?.length) {
    return (
      <div className="flex h-full flex-col items-center justify-center gap-3 py-8 text-center">
        <span className="text-2xl">⚠️</span>
        <p className="text-xs font-bold">{error || 'Could not generate quiz'}</p>
        <p className="text-[11px] text-muted-foreground max-w-[240px]">
          Ensure the webpage has text content and retry.
        </p>
        <div className="flex gap-2 mt-2">
          <Button size="sm" onClick={onRetry} className="rounded-full font-bold">Retry Quiz</Button>
          <Button variant="outline" size="sm" onClick={onBack} className="rounded-full">Back</Button>
        </div>
      </div>
    );
  }

  function choose(opt) {
    if (selected !== null) return;
    setSelected(opt);
    if (opt.trim().toLowerCase() === questions[current].answer.trim().toLowerCase()) {
      setScore((s) => s + 1);
    }
  }

  const q = questions[current];

  return (
    <div className="flex h-full flex-col gap-3 overflow-y-auto animate-fade-in">
      {!done ? (
        <>
          {/* Progress bar */}
          <div className="flex items-center gap-3">
            <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-muted">
              <div
                className="h-full bg-primary transition-all duration-300"
                style={{ width: `${((current + 1) / questions.length) * 100}%` }}
              />
            </div>
            <span className="rounded-full bg-muted/80 px-2 py-0.5 text-[10px] font-bold text-muted-foreground">
              Question {current + 1} of {questions.length}
            </span>
          </div>

          <p className="text-xs font-bold leading-5 text-foreground">{q.q}</p>

          {/* Options */}
          <div className="flex flex-col gap-2">
            {q.options?.map((opt, idx) => {
              let cls = 'border-border/70 bg-card hover:bg-accent';
              if (selected !== null) {
                if (opt.trim().toLowerCase() === q.answer.trim().toLowerCase()) {
                  cls = 'border-emerald-500 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 font-bold';
                } else if (opt === selected) {
                  cls = 'border-destructive bg-destructive/10 text-destructive';
                } else {
                  cls = 'border-border/40 bg-card opacity-50';
                }
              }
              return (
                <button
                  key={idx}
                  onClick={() => choose(opt)}
                  disabled={selected !== null}
                  className={`rounded-xl border p-2.5 text-left text-xs leading-4 transition-colors focus-visible:outline-none ${cls}`}
                >
                  <span className="mr-2 font-bold opacity-70">{String.fromCharCode(65 + idx)}.</span>
                  {opt}
                </button>
              );
            })}
          </div>

          {/* Explanation on selection */}
          {selected !== null && (
            <Card className="rounded-xl p-3 animate-fade-in border border-border/60">
              <div className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Explanation</div>
              <p className="mt-1 text-xs leading-relaxed text-muted-foreground">{q.explanation}</p>
              <Button
                size="sm"
                className="mt-3 w-full rounded-full font-bold shadow-hard-sm text-xs"
                onClick={() => {
                  if (current + 1 < questions.length) {
                    setCurrent((c) => c + 1);
                    setSelected(null);
                  } else {
                    setDone(true);
                  }
                }}
              >
                {current + 1 < questions.length ? 'Next Question →' : 'See Results'}
              </Button>
            </Card>
          )}
        </>
      ) : (
        <div className="flex flex-col items-center gap-4 py-8 text-center animate-fade-in">
          <span className="text-3xl">{score >= 4 ? '🏆' : score >= 2 ? '👏' : '📚'}</span>
          <span
            className={`rounded-full border px-4 py-1.5 text-sm font-black ${
              score >= 4
                ? 'border-emerald-500 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400'
                : score >= 2
                ? 'border-warning bg-warning/10 text-warning'
                : 'border-destructive bg-destructive/10 text-destructive'
            }`}
          >
            {score} / {questions.length} Correct
          </span>
          <p className="text-xs font-medium text-muted-foreground">
            {score >= 4 ? 'Outstanding comprehension! 🎉' : score >= 2 ? 'Good grasp of the concepts!' : 'Review the takeaways and try again.'}
          </p>
          <div className="flex gap-2">
            <Button
              onClick={() => {
                setCurrent(0);
                setSelected(null);
                setScore(0);
                setDone(false);
              }}
              className="rounded-full font-bold"
            >
              Try Again
            </Button>
            <Button variant="outline" onClick={onBack} className="rounded-full">
              Back to Tools
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
