export const CHROME_STORE_URL = 'https://chrome.google.com/webstore/detail/pagepal-ai/placeholder';

export const FEATURES = [
  {
    icon: '📄',
    title: 'Webpage Summary',
    description: 'Instantly summarize any article, blog, or docs into key insights — grounded in the page.',
    color: 'from-brand-500/20 to-purple-600/20',
    border: 'border-brand-500/20',
  },
  {
    icon: '🎥',
    title: 'YouTube Chapters',
    description: 'Extract key ideas + auto timestamps from any video. No more scrubbing hours.',
    color: 'from-red-500/20 to-orange-500/20',
    border: 'border-red-500/20',
  },
  {
    icon: '💬',
    title: 'Chat with Page',
    description: 'Ask anything — Claude/GPT/Gemini answer with citations from the actual content.',
    color: 'from-blue-500/20 to-cyan-500/20',
    border: 'border-blue-500/20',
  },
  {
    icon: '🔑',
    title: 'BYOK + Subscription',
    description: 'Use PagePal Pro ($9/mo, keys included) or bring your own API key — your quota, your control.',
    color: 'from-amber-500/20 to-yellow-500/20',
    border: 'border-amber-500/20',
  },
  {
    icon: '🧩',
    title: 'Quiz & Translate',
    description: 'Pro: 5 MCQs per page + translate summaries to 50+ languages in one click.',
    color: 'from-orange-500/20 to-amber-500/20',
    border: 'border-orange-500/20',
  },
  {
    icon: '⚡',
    title: '5 Models, Smart Router',
    description: 'Claude, GPT-4o, Gemini, DeepSeek, Grok — auto-selected or pick your own via BYOK.',
    color: 'from-cyan-500/20 to-blue-500/20',
    border: 'border-cyan-500/20',
  },
];

export const MODELS = [
  {
    name: 'Claude Sonnet 4',
    provider: 'Anthropic',
    icon: '🧠',
    color: 'from-violet-500 to-purple-500',
    bg: 'bg-violet-500/10',
    border: 'border-violet-500/20',
    textColor: 'text-violet-400',
    badge: 'Default • Subscription',
    badgeColor: 'bg-violet-500/20 text-violet-300',
    usedFor: 'Best overall — articles, PDFs, YouTube with high accuracy + timestamps',
    tag: 'Recommended',
  },
  {
    name: 'GPT-4o',
    provider: 'OpenAI',
    icon: '⚡',
    color: 'from-emerald-500 to-teal-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/20',
    textColor: 'text-emerald-400',
    badge: 'BYOK • Balanced',
    badgeColor: 'bg-emerald-500/20 text-emerald-300',
    usedFor: 'General Q&A, blogs, code explanations — bring your OpenAI key',
    tag: 'Bring your key',
  },
  {
    name: 'Gemini Flash',
    provider: 'Google',
    icon: '✦',
    color: 'from-blue-500 to-cyan-400',
    bg: 'bg-blue-500/10',
    border: 'border-blue-500/20',
    textColor: 'text-blue-400',
    badge: 'BYOK • Long Context',
    badgeColor: 'bg-blue-500/20 text-blue-300',
    usedFor: 'Huge articles, transcripts, 1M context — via your Gemini key',
    tag: '1M context',
  },
  {
    name: 'DeepSeek',
    provider: 'DeepSeek AI',
    icon: '🔍',
    color: 'from-orange-500 to-amber-500',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/20',
    textColor: 'text-orange-400',
    badge: 'BYOK • Code',
    badgeColor: 'bg-orange-500/20 text-orange-300',
    usedFor: 'Code, technical docs, 10× cheaper — use your DeepSeek key',
    tag: 'Best for code',
  },
  {
    name: 'Grok',
    provider: 'xAI',
    icon: '𝕏',
    color: 'from-zinc-500 to-zinc-400',
    bg: 'bg-zinc-500/10',
    border: 'border-zinc-500/20',
    textColor: 'text-zinc-300',
    badge: 'BYOK • Trending',
    badgeColor: 'bg-zinc-500/20 text-zinc-300',
    usedFor: 'News, X trends, real-time — via your xAI key',
    tag: 'Real-time',
  },
];

export const STEPS = [
  {
    number: '01',
    title: 'Install Extension',
    description: 'Add PagePal to Chrome in one click. Free. No signup required to start.',
    icon: '🔌',
  },
  {
    number: '02',
    title: 'Open Any Page',
    description: 'Navigate to any webpage, article, YouTube video, or documentation you want to understand.',
    icon: '🌐',
  },
  {
    number: '03',
    title: 'Click Summarize',
    description: 'Open the sidebar panel. Hit a quick action or ask your own question.',
    icon: '🧠',
  },
  {
    number: '04',
    title: 'Get Instant Results',
    description: 'PagePal selects the best AI model and delivers your summary in seconds.',
    icon: '✅',
  },
];

export const STATS = [
  { value: 'Claude 4', label: 'Powered by Anthropic' },
  { value: '5/day',  label: 'Free Summaries' },
  { value: 'Pro $9',    label: 'Unlimited + Translate & Quiz' },
  { value: '< 3s', label: 'Avg Response Time' },
];
