"use strict";

const mongoose = require("mongoose");

const conversationSchema = new mongoose.Schema(
  {
    // UUID generated by the server (or forwarded from the client)
    conversationId: {
      type: String,
      required: [true, "conversationId is required"],
      unique: true,
    },

    // The user this conversation belongs to
    userId: {
      type: String,
      trim: true,
    },

    // The URL of the page where this conversation started
    pageUrl: {
      type: String,
      trim: true,
    },

    // Human-readable title of the page
    pageTitle: {
      type: String,
      trim: true,
    },

    createdAt: {
      type: Date,
      default: Date.now,
    },

    // Updated whenever a new message is added
    updatedAt: {
      type: Date,
      default: Date.now,
    },

    // Cached count — avoids a COUNT query on every conversation list fetch
    messageCount: {
      type: Number,
      default: 0,
    },

    // Soft-delete flag; set to false instead of removing documents
    isActive: {
      type: Boolean,
      default: true,
    },
  },
  {
    versionKey: false,
  },
);

// Note: conversationId already has a unique index from { unique: true } above.
// No need to add it again with .index() — that caused the Mongoose duplicate warning.

// Support listing conversations by user, sorted by recency
conversationSchema.index({ userId: 1, updatedAt: -1 });

module.exports = mongoose.model("Conversation", conversationSchema);
